name: All Manner of Nonsense
url: http://grepory.github.io
description: Mostly coding, most of the time.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
